aws/fmeval

- src/fmeval/eval_algorithms/classification_accuracy_semantic_robustness.py
> fix: remove unnecessary code

- src/fmeval/eval_algorithms/__init__.py
fix: update the default prompt template for boolq dataset
> fix: update the default prompt template for boolq dataset

- poetry.lock
- pyproject.toml
chore: update ray version to fix  errors in Mac M1 laptops
> chore: update ray version to fix  errors in Mac M1 laptops

- src/fmeval/eval_algorithms/qa_accuracy.py
> fix: fix f1_score

- src/fmeval/model_runners/sm_jumpstart_model_runner.py
- src/fmeval/model_runners/sm_model_runner.py
- test/unit/model_runners/test_sm_jumpstart_model_runner.py
- test/unit/model_runners/test_sm_model_runner.py
Support inference component feature https://github.com/aws/sagemaker-python-sdk/commit/3ee0b13b5cf65ca0dcb74f2d17e704d96b0e09aa
> feat: support inference component

- pyproject.toml
Bump up fmeval version to 0.3.0.
> build: bump fmeval version to 0.3.0

- src/fmeval/eval_algorithms/util.py
This PR replaces the last instance of `dataset.add_column` (which I somehow missed when submitting [PR #115](https://github.com/aws/fmeval/pull/115)) with `dataset.map`. Note that this PR is not necessary for correctness, but simply to make our code uniform (since it's kind of weird to have just one function that uses `add_column` while all of them use `map`).
Note: a question that likely arises is "How come the integration test that was added to `test_factual_knowledge.py` (which was supposed to validate the fix) was able to pass, given that `_generate_prompt_column` was still using `add_column`, which should've caused inconsistencies in the batch formats in the Ray task graph?"
The reason the test passed despite me not replacing *every* …
> fix: replace add_column with map in _generate_prompt_column

- src/fmeval/eval_algorithms/__init__.py
- src/fmeval/reporting/constants.py
- test/unit/eval_algorithms/test_summarization_accuracy.py
- test/unit/eval_algorithms/test_summarization_accuracy_semantic_robustness.py
- test/unit/eval_algorithms/test_summarization_toxicity.py
- test/unit/reporting/test_eval_output_cells.py
> chore: remove xsum dataset and update gigaword description

- src/fmeval/reporting/constants.py
* Add metric description for BERTScore Dissimilarity metric. 
> fix: add bert_score_dissimilarity description

- README.md
#197 
docs: add troubleshooting item for OOM errors
> docs: add troubleshooting item for OOM errors

- README.md
- src/fmeval/model_runners/sm_jumpstart_model_runner.py
> fix: update terminology in README and source code

- README.md
This PR adds information to the troubleshooting section regarding Windows-specific issues that users may run into.
> docs: update README to include information about Windows support

- src/fmeval/eval_algorithms/general_semantic_robustness.py
- src/fmeval/eval_algorithms/qa_accuracy.py
- src/fmeval/eval_algorithms/semantic_robustness_utils.py
- src/fmeval/eval_algorithms/summarization_accuracy_semantic_robustness.py
- src/fmeval/eval_algorithms/util.py
- test/unit/eval_algorithms/test_qa_accuracy.py
- test/unit/eval_algorithms/test_util.py
> feat: update implementation of QAAccuracy to use Transform-based approach

- src/fmeval/eval_algorithms/qa_accuracy_semantic_robustness.py
- test/integration/test_qa_accuracy_semantic_robustness.py
- test/unit/eval_algorithms/test_qa_accuracy_semantic_robustness.py
> feat: update implementation of QAAccuracySemanticRobustness to use Transform-based approach

- src/fmeval/eval_algorithms/classification_accuracy.py
- src/fmeval/eval_algorithms/qa_accuracy.py
- test/unit/eval_algorithms/test_classification_accuracy.py
> feat: update implementation of ClassificationAccuracy to use Transform-based approach

- src/fmeval/eval_algorithms/classification_accuracy_semantic_robustness.py
- src/fmeval/eval_algorithms/qa_accuracy_semantic_robustness.py
- test/integration/test_classification_accuracy_semantic_robustness.py
- test/unit/eval_algorithms/test_classification_accuracy_semantic_robustness.py
- test/unit/eval_algorithms/test_qa_accuracy_semantic_robustness.py
> feat: update implementation of ClassificationAccuracySemanticRobustness to use Transform-based approach

- THIRD-PARTY-LICENSES
* Updating third party attributions
* Attributions file approval ticket: https://tiny.amazon.com/eh6644x0
> Updating third party attributions

- src/fmeval/eval_algorithms/factual_knowledge.py
- test/integration/test_factual_knowledge.py
- test/unit/eval_algorithms/test_factual_knowledge.py
> feat: update implementation of FactualKnowledge to use Transform-based approach

- pyproject.toml
> build: bump fmeval version to 1.0.0

- README.md
Update README with details on contributing new eval algos.
> docs: update README with details on contributing new eval algos

- pyproject.toml
Bump fmeval version to 1.0.1 for release. 
> build: bump fmeval version to 1.0.1

- pyproject.toml
> Revert "build: bump fmeval version to 1.0.1"

- README.md
*Issue #, if available:* N/A
*Description of changes:* Add syntax highlighting, particularly nice for the Python code
> docs: add syntax highlighting

- pyproject.toml
> build: bump fmeval version to 1.0.2

- pyproject.toml
> build: bump fmeval version to 1.0.3

- src/fmeval/eval_algorithms/util.py
- test/unit/eval_algorithms/test_util.py
Add validate_prompt_template util function.
> feat: add validate_prompt_template util

- src/fmeval/transforms/common.py
Fix https://github.com/aws/fmeval/pull/288#discussion_r1639000895
> fix: register placeholder_to_record_key in GeneratePrompt transform

- pyproject.toml
NA
Bumping the fmeval version for Pypi release.
> build: bump fmeval version to 1.2.1
