poetry.lock
pyproject.toml

1. update sagemaker to 2.198.0
2. update s3fs to 2023.12.0
3. update the license info from `Proprietary` to  `Apache License 2.0`

build: update sagemaker to 2.198.0, license type to Apache

---

poetry.lock
src/fmeval/model_runners/extractors/jumpstart_extractor.py
test/unit/model_runners/extractors/test_jumpstart_extractor.py

fix: update Jumpstart errors to EvalAlgorithmInternalError since they are not client errors but errors in Jumpstart or fmeval 

fix: update Jumpstart errors to EvalAlgorithmInternalError

---

poetry.lock
pyproject.toml

Bump up fmeval version to 0.2.1.

build: Bump fmeval version to 0.2.1

---

src/fmeval/reporting/constants.py

*Issue #, if available:* https://tiny.amazon.com/ulr8y9tp
- add string replacement for capitalizing `SageMaker`.

fix: add proper capitalization for 'SageMaker'

---

devtool
poetry.lock
pyproject.toml
src/fmeval/data_loaders/data_sources.py
src/fmeval/data_loaders/util.py
src/fmeval/model_runners/util.py
test/unit/data_loaders/test_data_sources.py
test/unit/data_loaders/test_util.py

This PR removes all usages of the `s3fs` from the code and removes `s3fs` from `pyproject.toml` (done via the command `poetry remove s3fs`). This PR additionally introduces the `boto3-stubs` package, which allows for boto3 type annotations.

fix: remove s3fs from data-loading code and use boto3 instead

---

src/fmeval/model_runners/bedrock_model_runner.py
src/fmeval/model_runners/sm_jumpstart_model_runner.py
src/fmeval/model_runners/sm_model_runner.py

*Issue*: when subclassing Jumpstart/SM/Bedrock model runners one has also to override the `__reduce__` function to change the returned class, which is not intuitive 
*Description of changes:* changed return of `__reduce__` functions to `self.__class__` rather than (e.g.) `BedrockRunner`, making overriding of __reduce__ optional (and very likely not necessary).

feat: make sm/br runners easier to subclass

---

src/fmeval/eval_algorithms/qa_accuracy.py
test/unit/eval_algorithms/test_qa_accuracy.py

*Description of changes:* Strip the model output and the target text when computing the F1 score. With this change, the strings with an without trailing / leading whitespace characters will be considered equivalent (e.g., "yes" and "yes\n"). We need this change because FMs often include newline characters in their output.

Update f1 score in QA accuracy eval

---

src/fmeval/eval_algorithms/qa_accuracy.py
test/unit/eval_algorithms/test_qa_accuracy.py

Prior to this PR, we strip the text when computing f1_score but not when computing precision and recall. This PR makes the stripping functionality uniform across all three metrics.

Strip text when computing precision and recall.

---

devtool

https://github.com/aws/fmeval/issues/162. 
update devtool all to install first, lint after. This PR should fix `./devtool: line 14: pre-commit: command not found`

chore: update devtool all to install first, lint after

---

.github/workflows/unit_test_coverage.yml
devtool
test/unit/example_notebooks/test_example_notebooks.py

After PR #180, we've been consistently running into issues where pip installing `fmeval` from pypi within the example notebooks (this installation is always included as the first cell of the notebooks) is causing dependency version issues that cause the `test_custom_model_hf_notebook` test to fail.
Specifically, `tokenizers` is getting re-installed to be a lower version (`0.12.1`) that is used by the current release of `fmeval` , but `transformers` somehow isn't also getting re-installed to its lower version (`4.22.1`); it's still `4.37.2` as dictated by `pyproject.toml`.
This PR updates the example notebook unit tests so that they do not install `fmeval` from pypi. Rather they will continue to use the `fmeval` package installed by poetry during `poetry install`, …

fix: Fix example notebook unit tests

---

poetry.lock
pyproject.toml

This PR simply updates the required version of `ray` to `2.9.1`. `2.9.1` contains an important bugfix that ensures that when a Ray Dataset is constructed from reading a file that is local to a node, the read operation will not get performed on any other nodes. While not required reading, see this [issue](https://github.com/ray-project/ray/issues/42749) I raised for additional context.

chore: Update Ray to 2.9.1

---

src/fmeval/transforms/transform.py
test/unit/transforms/test_transform.py

This PR implements the `Transform` abstract base class, which is the fundamental "building block" used in the new, modular design for implementing evaluation algorithms and metrics.

feat: implement Transform abstract base class

---

src/fmeval/transforms/common.py
src/fmeval/transforms/transform.py
src/fmeval/transforms/util.py
test/unit/transforms/test_common.py
test/unit/transforms/test_transform.py
test/unit/transforms/test_util.py

This PR implements two utility transforms: one for generating prompts from raw text input, and another for invoking model runners. It also implements a few validation utility functions that will be used across all `Transform`s that we implement.

feat: implement GeneratePrompt and GetModelResponse utility transforms

---

src/fmeval/constants.py
src/fmeval/transforms/transform.py
src/fmeval/transforms/transform_pipeline.py
test/integration/transforms/test_transform_pipeline.py
test/unit/transforms/test_transform.py
test/unit/transforms/test_transform_pipeline.py

This PR implements the `TransformPipeline` class, which is used to apply `Transform`s to a Ray `Dataset`. The PR additionally adds some new validations to the `Transform` initializer.

feature: implement TransformPipeline

---

src/fmeval/transforms/common.py
src/fmeval/transforms/util.py
test/unit/transforms/test_common.py

This PR includes the implementation of a decorator that performs input/output validation of a `Transform`'s `__call__` method. It cleans up the existing code such that we don't have to manually invoke the same boilerplate code every time.

feat: implement validate_call decorator

---

src/fmeval/helper_models.py
src/fmeval/util.py
test/integration/test_util.py
test/unit/test_helper_models.py
test/unit/test_util.py

This PR ports over a copy of the helper models from `fmeval.eval_algorithms.helper_models.helper_model` into `fmeval.helper_models`. The reason behind keeping the old code is that I don't to make half-baked changes that will break the existing evaluation algorithm implementations. Eventually, when all evaluation algorithms use the new Transform-based design, I will obviously get rid of `fmeval.eval_algorithms.helper_models.helper_model`.
Note that the new helper model code isn't _exactly_ the same as the original code, but the changes are mainly minor cleanup.
This PR also implements the `create_shared_resource` utility function, which is used to create a Ray actor out of a "shared resource" (which is typically an object that consumes lots of memory, like a …

feat: implement helper models used by evaluation algorithms

---

src/fmeval/transforms/summarization_accuracy_metrics.py
test/unit/test_util.py
test/unit/transforms/test_summarization_accuracy_metrics.py

This PR implements `Transform`s for the three existing summarization accuracy metrics supported by `fmeval`: Meteor, Rouge, and Bert.

feat: implement transforms for summarization accuracy metrics

---

src/fmeval/eval_algorithms/summarization_accuracy.py
src/fmeval/transforms/common.py
src/fmeval/transforms/semantic_perturbations.py
src/fmeval/transforms/summarization_accuracy_metrics.py
src/fmeval/transforms/transform.py
src/fmeval/transforms/transform_pipeline.py
test/integration/transforms/test_transform_pipeline.py
test/unit/eval_algorithms/test_summarization_accuracy.py
test/unit/transforms/test_common.py
test/unit/transforms/test_semantic_perturbations.py
test/unit/transforms/test_summarization_accuracy_metrics.py
test/unit/transforms/test_transform.py
test/unit/transforms/test_transform_pipeline.py

This PR makes the following changes:
1. Update `GetModelResponse` and all three summarization accuracy metric transforms to support multiple input keys
2. Update `TransformPipeline.execute` to materialize intermediate datasets (as I've observed that not materializing the dataset leads to a performance degradation in `SummarizationAccuracy` evaluations). This change causes the performance of `SummarizationAccuracy` to match the performance of the old code.
3. Refactor the summarization accuracy metrics to use a parent ABC, mimicking the approach taken with the semantic perturbation transforms.
4. Fix bug in `semantic_perturbations.py` where I didn't unpack `*args` and `**kwargs`. Updated the unit test to catch this bug.
By submitting this pull request, I confirm …

feat: update various transforms to accept multiple input keys

---

src/fmeval/eval_algorithms/summarization_accuracy.py
src/fmeval/transforms/common.py
test/integration/transforms/test_transform_pipeline.py
test/unit/eval_algorithms/test_summarization_accuracy.py
test/unit/transforms/test_common.py

This PR updates `GetModelResponse` so that it supports the semantic robustness use case where a model is invoked on the same input multiple times.
Currently, the instance attribute `input_to_output_keys` maps a model input key to a list representing the model response keys (where a response is of the form `(model_output, log_probability)` where both `model_output` and `log_probability` are optional).
This PR changes `input_to_output_keys` such that a model input key is mapped to a list of tuples, where each tuple is of the form `(model_output, log_probability)`.

feat: update GetModelResponse transform to support multiple model invocations on the same input

---

src/fmeval/constants.py
src/fmeval/eval_algorithms/classification_accuracy_semantic_robustness.py
src/fmeval/eval_algorithms/general_semantic_robustness.py
src/fmeval/eval_algorithms/qa_accuracy_semantic_robustness.py
src/fmeval/eval_algorithms/summarization_accuracy_semantic_robustness.py
src/fmeval/transforms/common.py
src/fmeval/transforms/semantic_robustness_metrics.py
src/fmeval/transforms/transform_pipeline.py
src/fmeval/transforms/util.py
test/integration/test_classification_accuracy_semantic_robustness.py
test/integration/test_general_semantic_robustness.py
test/integration/test_qa_accuracy_semantic_robustness.py
test/integration/test_summarization_accuracy_semantic_robustness.py
test/unit/eval_algorithms/test_classification_accuracy_semantic_robustness.py
test/unit/eval_algorithms/test_general_semantic_robustness.py
test/unit/eval_algorithms/test_qa_accuracy_semantic_robustness.py
test/unit/eval_algorithms/test_summarization_accuracy_semantic_robustness.py
test/unit/eval_algorithms/test_util.py
test/unit/transforms/test_common.py
test/unit/transforms/test_semantic_robustness_metrics.py
test/unit/transforms/test_transform_pipeline.py
test/unit/transforms/test_util.py

This PR updates the `GeneralSemanticRobustness` algorithm such that evaluation logic is implemented via the use of `Transform`s. This PR is analogous to #214, but for General Semantic Robustness (GSR).
The diff indicates that many files have been changed, but all of the changes to code that is not related to GSR are due to my renaming of some constants (`RANDOM_UPPER_CASE` -> `RANDOM_UPPERCASE` and `WHITESPACE_ADD_REMOVE` -> `ADD_REMOVE_WHITESPACE`).
The main files to review are the following:
- [src/fmeval/eval_algorithms/general_semantic_robustness.py](https://github.com/aws/fmeval/compare/main...danielezhu:fmeval:gsr?expand=1#diff-d9531d2c2473c43760c708bfdedb205b4cfe89efeb9e108b2554937df63ecd9a) which obviously contains the new implementation of GSR.
- …

feat: update implementation of GeneralSemanticRobustness to use Transform-based approach

---

src/fmeval/eval_algorithms/general_semantic_robustness.py
src/fmeval/eval_algorithms/summarization_accuracy.py
src/fmeval/transforms/common.py
test/integration/transforms/test_transform_pipeline.py
test/unit/eval_algorithms/test_general_semantic_robustness.py
test/unit/eval_algorithms/test_summarization_accuracy.py
test/unit/transforms/test_common.py

Currently, `GetModelResponse` is a transform that augments the input record with the entire model response payload from calling the `predict` method of a `ModelRunner`. The response payload is of the form `(model_output, log_prob)`, where both `model_output` and `log_prob` are optional, and whether they are non-null depends on the particular `ModelRunner` being used.
When initializing a `GetModelResponse`, one must provide a tuple representing the keys that will be associated with the data in a response payload. Algorithms like `SummarizationAccuracy` that currently utilize `GetModelReponse` only care about obtaining model outputs (and not the log probabilities), and thus only provide a key for the model output when constructing `GetModelResponse` instances.
The …

fix: update GetModelResponse transform to work with any ModelRunner

---

src/fmeval/constants.py
src/fmeval/eval_algorithms/classification_accuracy_semantic_robustness.py
src/fmeval/eval_algorithms/general_semantic_robustness.py
src/fmeval/eval_algorithms/qa_accuracy_semantic_robustness.py
src/fmeval/eval_algorithms/summarization_accuracy_semantic_robustness.py
test/integration/test_classification_accuracy_semantic_robustness.py
test/integration/test_general_semantic_robustness.py
test/integration/test_qa_accuracy_semantic_robustness.py
test/integration/test_summarization_accuracy_semantic_robustness.py
test/unit/eval_algorithms/test_classification_accuracy_semantic_robustness.py
test/unit/eval_algorithms/test_general_semantic_robustness.py
test/unit/eval_algorithms/test_qa_accuracy_semantic_robustness.py
test/unit/eval_algorithms/test_summarization_accuracy_semantic_robustness.py

Certain software relies on these constants, so they should not have been changed by #222. This PR simply reverts the renamings introduced in #222.

fix: restore semantic perturbation constants to their original values

---

src/fmeval/eval_algorithms/classification_accuracy.py
src/fmeval/eval_algorithms/classification_accuracy_semantic_robustness.py
src/fmeval/eval_algorithms/eval_algorithm.py
src/fmeval/eval_algorithms/factual_knowledge.py
src/fmeval/eval_algorithms/general_semantic_robustness.py
src/fmeval/eval_algorithms/prompt_stereotyping.py
src/fmeval/eval_algorithms/qa_accuracy.py
src/fmeval/eval_algorithms/qa_accuracy_semantic_robustness.py
src/fmeval/eval_algorithms/semantic_robustness_utils.py
src/fmeval/eval_algorithms/summarization_accuracy.py
src/fmeval/eval_algorithms/summarization_accuracy_semantic_robustness.py
src/fmeval/eval_algorithms/toxicity.py
src/fmeval/eval_algorithms/util.py
src/fmeval/util.py
test/unit/eval_algorithms/test_general_semantic_robustness.py
test/unit/eval_algorithms/test_summarization_accuracy.py
test/unit/test_util.py

Aside from updating the interface method signatures, this PR also makes some small updates to `SummarizationAccuracy` and address some comments that were left on #224.

chore: restore evaluate_sample and evaluate signatures in EvalAlgorithmInterface

---

devtool
src/fmeval/eval_algorithms/general_semantic_robustness.py
src/fmeval/eval_algorithms/helper_models/helper_model.py
src/fmeval/eval_algorithms/summarization_accuracy_semantic_robustness.py
src/fmeval/transforms/semantic_robustness_metrics.py
src/fmeval/transforms/summarization_accuracy_metrics.py
test/integration/test_summarization_accuracy_semantic_robustness.py
test/integration/test_util.py
test/unit/eval_algorithms/test_general_semantic_robustness.py
test/unit/eval_algorithms/test_helper_model.py
test/unit/eval_algorithms/test_summarization_accuracy.py
test/unit/eval_algorithms/test_summarization_accuracy_semantic_robustness.py
test/unit/transforms/test_semantic_robustness_metrics.py
test/unit/transforms/test_summarization_accuracy_metrics.py

See title. This PR also fixes a bug introduced in the previous PR where the `invoke_model` call in `BertScore` was not replaced with `get_helper_scores`.

feat: update implementation of SummarizationAccuracySemanticRobustness to use Transform-based approach

---

src/fmeval/eval_algorithms/eval_algorithm.py
src/fmeval/eval_algorithms/prompt_stereotyping.py
src/fmeval/transforms/common.py
test/unit/eval_algorithms/test_prompt_stereotyping.py
test/unit/transforms/test_common.py

Title. Also removed `model` from the `evaluate_sample` signature in the interface, which I mistakenly added in a previous PR.

feat: update implementation of PromptStereotyping to use Transform-based approach

---

src/fmeval/constants.py
src/fmeval/data_loaders/util.py

Set s3 boto3 client region to `us-west-2` when accessing built-in datasets to fix invalid dataset path issue in opt-in regions. 

fix: set default region for boto3 client to access built-in datasets

---

src/fmeval/data_loaders/data_sources.py
src/fmeval/data_loaders/util.py
test/unit/data_loaders/test_data_sources.py
test/unit/data_loaders/test_util.py

- fix s3 uri validation for built-in datasets by creating boto3 client with  `us-west-2` region.

fix: fix s3 uri validation for built-in datasets

---

src/fmeval/transforms/util.py
test/unit/transforms/test_common.py
test/unit/transforms/test_util.py

This PR relaxes the validation done in `validate_call` to only check if the keys in the `self.output_keys` attribute of the `Transform` are present in the output of `__call__`. Previously, we checked that the set difference between the current keys and the original keys is exactly equal to `self.output_keys`, but this validation is too strict for the BYO model outputs use case, where `GetModelOutputs` should overwrite existing model outputs in the record without validations failing.

fix: update output record key validation logic in validate_call

---

src/fmeval/model_runners/util.py
test/unit/model_runners/test_util.py

This PR removes the redundant creation of botocore configs (which are just duplicates of the config used in `get_boto_session`) found in `get_sagemaker_session` and `get_bedrock_runtime_client`.
Since we set the default client config used by the botocore session underlying the boto3 session that is used to create all of our clients (sagemaker, bedrock, etc), we don't need to pass the `config` parameter to `.client()`.
Note that it is very awkward to validate that the correct botocore config (i.e. our adaptive retry config) gets used when we create the sagemaker and bedrock clients, so I have not added a new unit test that checks this. Here is the logic flow for how the default botocore config ends up getting used:
1. `boto3.session.Session.client` is called with …

chore: simplify botocore/boto3-related util code

---

.github/workflows/docs.yml
poetry.lock
pyproject.toml

This PR adds a Github Actions workflow that generates documentation for `fmeval` in the form of html files via [pdoc](https://pdoc.dev/). These html files are then used by the `fmeval` repo's Github Pages site.
Note that using `pdoc` is nothing new; we already used `pdoc` to generate library documentation in the past (see the [docs branch](https://github.com/aws/fmeval/tree/docs) of this repo). Currently, the `fmeval` repo is configured to update the Github Pages site whenever a new commit is made to the `docs` branch. This isn't ideal, since it means that for virtually every commit, we have to manually checkout the `docs` branch, run `pdoc` to generate the updated documentation, then push the changes to the remote `docs` branch. Notice how we have not done this …

docs: create Github Actions workflow for generating docs via pdoc

---

test/unit/data_loaders/test_data_sources.py
test/unit/data_loaders/test_util.py
test/unit/model_runners/test_util.py

A couple unit tests are incorrectly using `"src.fmeval"` instead of just `"fmeval"` when patching functions. As a result, tests like `test_get_user_agent_extra` are calling the _actual function_  instead. In hindsight, I should've used a different `return_value` when patching `fmeval.model_runners.util.get_fmeval_package_version` so that this would've been easily caught.

fix: fix patching in unit tests

---

README.md
devtool
src/fmeval/model_runners/util.py

This PR contains edits to documentation regarding telemetry details. It also updates `devtool` to use `poetry check --lock` instead of the now-deprecated `poetry lock --check` command.

docs: update telemetry-related info in README and docstrings

---

src/fmeval/constants.py
src/fmeval/model_runners/extractors/jumpstart_extractor.py
test/unit/model_runners/extractors/test_jumpstart_extractor.py

Fetch log probability jmespath from JS metadata. This is a non-breaking change. 
We were using a constant path, and so far that was also correct. But, going forward, for new models, it might not be. It is better to fetch the jmespath directly from metadata. 

feat: fetch log probability jmespath from JS metadata

---

src/fmeval/constants.py
src/fmeval/data_loaders/data_config.py
src/fmeval/data_loaders/json_parser.py
test/unit/data_loaders/test_json_data_loader.py
test/unit/data_loaders/test_json_parser.py

**Update**: Initially we planned on the `target_context` dataset column taking list of strings. This does not work with ray operations such as `map_batches` due to issues including https://github.com/ray-project/ray/issues/39559 and other unsupported data type errors. Thus the `target_context` dataset column has been modified to take a string, and we will use string concatenation when there are multiple target contexts, similar to the existing `target_output` field.
**Description (updated)**:
* Adds support for loading `target_context` for evaluation of RAG "ground truth" context provided in a dataset. The `target_context` for each dataset sample is a ~~list of~~ string. 
* ~~Modifies `json_parser` to accept lists of strings by updating …

feat: add target_context to dataset columns

---

src/fmeval/transforms/common.py
test/unit/transforms/test_common.py
test/unit/transforms/test_transform_pipeline.py

Currently GeneratePrompt transform can only substitute default placeholder `$model_input` with `data` field. 
This PR will support `placeholder_data_dict` (https://github.com/aws/fmeval/pull/273)
`placeholder_keys_dict` will be placeholder keys to input keys mapping, but in this way it only supports transform 1 prompt with one placeholder dict. See unit test for use case

feat: modify GeneratePrompt transform to take placeholder_dict

---

src/fmeval/eval_algorithms/classification_accuracy.py
src/fmeval/eval_algorithms/classification_accuracy_semantic_robustness.py
src/fmeval/eval_algorithms/eval_algorithm.py
src/fmeval/eval_algorithms/factual_knowledge.py
src/fmeval/eval_algorithms/general_semantic_robustness.py
src/fmeval/eval_algorithms/prompt_stereotyping.py
src/fmeval/eval_algorithms/qa_accuracy.py
src/fmeval/eval_algorithms/qa_accuracy_semantic_robustness.py
src/fmeval/eval_algorithms/summarization_accuracy.py
src/fmeval/eval_algorithms/summarization_accuracy_semantic_robustness.py
src/fmeval/eval_algorithms/toxicity.py
src/fmeval/eval_algorithms/util.py
test/integration/test_factual_knowledge.py
test/unit/eval_algorithms/test_util.py

**Issue #, if available:** #269
**Description of changes:**
Extend `EvalAlgorithmInterface.evaluate()` interface to support specifying a list of multiple `data_config` objects. evaluate() already returns a list of results by dataset, because when run with no `data_config` argument all applicable built-in datasets are analyzed. As mentioned in the attached issue, it was weird and confusing that users couldn't explicitly specify a set of more than one datasets to use.
**Testing done:**
- Added unit tests to cover all scenarios of `get_dataset_configs()`
- Added one integration test to validate multi-dataset functionality for the only evaluator (`FactualKnowledge`) where multiple integration test datasets had already been defined.
<br/>
By submitting this pull request, I confirm that you can …

Support multiple data configs in evaluate

---

src/fmeval/eval_algorithms/__init__.py
src/fmeval/eval_algorithms/helper_models/helper_model.py
src/fmeval/reporting/constants.py
test/unit/eval_algorithms/test_eval_algorithm.py
test/unit/eval_algorithms/test_helper_model.py

**Issue #, if available:** #186
**Description of changes:**
- Update all string enums to inherit from `(str, Enum)` so that comparisons work as expected
- Add unit tests to cover equality comparisons
**Testing done:**
Ran `./devtool all` and all tests completed successfully
<br/>

Fix comparisons for string enumerations

---

src/fmeval/constants.py
src/fmeval/model_runners/bedrock_model_runner.py
src/fmeval/model_runners/composers/__init__.py
src/fmeval/model_runners/composers/jumpstart_composer.py
src/fmeval/model_runners/extractors/__init__.py
src/fmeval/model_runners/extractors/extractor.py
src/fmeval/model_runners/extractors/json_extractor.py
src/fmeval/model_runners/extractors/jumpstart_extractor.py
src/fmeval/model_runners/model_runner.py
src/fmeval/model_runners/sm_jumpstart_model_runner.py
src/fmeval/model_runners/sm_model_runner.py
src/fmeval/model_runners/util.py
test/unit/model_runners/composers/test_jumpstart_composer.py
test/unit/model_runners/extractors/test_create_extractor.py
test/unit/model_runners/extractors/test_jumpstart_extractor.py
test/unit/model_runners/test_bedrock_model_runner.py
test/unit/model_runners/test_sm_jumpstart_model_runner.py
test/unit/model_runners/test_sm_model_runner.py
test/unit/model_runners/test_util.py

Support text embedding model runner.
1. add `embedding` jmes path filed for model runners 
2. if `embedding` field can be extracted from `predict` model output, then return

feat: support embedding model runner

---

src/fmeval/constants.py
src/fmeval/data_loaders/data_config.py
src/fmeval/eval_algorithms/__init__.py
src/fmeval/eval_algorithms/common.py
src/fmeval/eval_algorithms/context_quality.py
test/unit/eval_algorithms/test_context_quality.py

This PR adds the context precision metric under the context quality evaluation algorithm. This is the first of three evaluation metrics under context quality. 
Context Precision is a metric that evaluates whether all of the target output relevant items present in the retrieved contexts are ranked higher or not. Ideally all the relevant context chunks must appear at the top ranks. This metric is computed using the `model_input`, `target_output` and the `retrieved_contexts`, with values ranging between 0 and 1, where higher scores indicate better precision.
Notes:
* There are no built in datasets for context quality since the dataset context needs to be retrieved by the RAG system. 
* The default judge model is currently set to a sample …

feat: add context precision for context quality eval algo

---

src/fmeval/constants.py
src/fmeval/eval_algorithms/__init__.py
src/fmeval/eval_algorithms/util.py
test/unit/eval_algorithms/test_common.py
test/unit/eval_algorithms/test_eval_algorithm.py
test/unit/eval_algorithms/test_util.py

Add error fields in `EvalScore`. Ignore None value when aggregate dataset score.

feat: add error field in EvalScore

---

src/fmeval/eval_algorithms/faithfulness.py
test/unit/eval_algorithms/test_faithfulness.py

Handle edge case when no statements being generated from judge model.
1. Rebased from https://github.com/aws/fmeval/pull/297.
2. Generate error in EvalScore if no statements

feat: faithfulness handle no statements edge case

---

src/fmeval/eval_algorithms/context_quality.py

This code: `denominator = sum(model_verdicts) + 1e-10` will lead to inaccurate context precision score when `sum(model_verdicts) > 0` and `numerator > 0`. For example: `1 / (1 + 1e-10) = 0.9999999999`
Fixed this by returning `0` if `sum(model_verdicts)` is `0`.

fix: Context precision score computation

---

src/fmeval/constants.py
src/fmeval/data_loaders/data_sources.py
test/unit/data_loaders/test_data_sources.py

* Update `get_s3_client` for us-isof partition. Built-in datasets are located in `us-isof-south-1` region. (`verify` is set to false because there are issues with SSL verification in the partition).

feat: update s3 data source for us-isof partition

---

src/fmeval/eval_algorithms/factual_knowledge.py
src/fmeval/reporting/constants.py
src/fmeval/reporting/eval_output_cells.py
test/integration/test_factual_knowledge.py
test/unit/eval_algorithms/test_factual_knowledge.py

This PR updates the names of the factual knowledge scores such that the changes to the factual knowledge algorithm from #302 are not breaking changes. Currently, we are removing the `FACTUAL_KNOWLEDGE` constant from the `factual_knowledge` module and renaming the scores that get output by the algorithm. These are incompatible API changes, and according to [semantic versioning](https://semver.org/), this would require us to bump the major version when performing the next release.

chore: rename factual knowledge scores

---

pyproject.toml

Version bump. Bumping minor version since semantic versioning states that you should bump the minor version "when you add functionality in a backward compatible manner". We actually should've been bumping the minor version instead of the patch version for several of the past releases.

build: bump fmeval version to 1.1.0

---

poetry.lock
pyproject.toml

Build failed due to nltk version update, so I downgraded the version to temporarily fix the issue.
Here's the error that was generated: 
```
E       LookupError:
--
4975 | E       **********************************************************************
4976 | E         Resource punkt_tab not found.
4977 | E         Please use the NLTK Downloader to obtain the resource:
4978 | E
4979 | E         >>> import nltk
4980 | E         >>> nltk.download('punkt_tab')
4981 | E
4982 | E         For more information see: https://www.nltk.org/data.html
4983 | E
4984 | E         Attempted to load tokenizers/punkt_tab/english/
4985 | E
4986 | E         Searched in:
4987 | E           - '/root/nltk_data'
4988 | E           - '/codebuild/output/src862412924/src/venv/nltk_data'
4989 | E           - …
```

build(deps): pinned nltk version to address build failure

---

src/fmeval/model_runners/extractors/jumpstart_extractor.py
test/unit/model_runners/composers/test_jumpstart_composer.py
test/unit/model_runners/extractors/test_create_extractor.py
test/unit/model_runners/extractors/test_jumpstart_extractor.py
test/unit/model_runners/test_sm_jumpstart_model_runner.py
test/unit/model_runners/test_util.py

Tests are failing because of deprecated model being used.
Removing `cohere-gpt-medium` model since it is no longer available.
Instead adding new proprietary model `ai21-summarization`.

fix: remove deprecated proprietary model id

---

poetry.lock
pyproject.toml

1. update tornado version due to security vulnerability in version 6.4.2 to address CVE: `CVE-2024-52804`

build(deps) : update tornado to 6.4.2

---

.github/workflows/unit_test_coverage.yml

*Issue #
*Description of changes: Ensure that your GitHub workflows cannot be automatically triggered when a non-contributor submits a pull request or using similar event. Especially if you have workflows that run integration tests, please ensure a [manual approval](https://github.com/aws/sagemaker-python-sdk/blob/master/.github/workflows/codebuild-ci.yml#L39) step is added before triggering the workflow.

add-workflow-approval
